security:
   encoders:
       Symfony\Component\Security\Core\User\User: plaintext
       Quiz\LectureQuizBundle\Entity\User:
             algorithm:            bcrypt
             cost:                 7

   role_hierarchy:
       ROLE_ADMIN: [ROLE_USER]

   providers:
       chain_provider:
          chain:
             providers: [in_memory, user_db]
       in_memory:
             memory:
                users:
                   admin: { password: adminpass, roles: ROLE_ADMIN }
       user_db:
             entity: { class: QuizLectureQuizBundle:User, property: username }

   firewalls:
       main:
         remember_me:
              key: "%secret%"
              lifetime: 31536000 #365 days in seconds
              path: /
              domain: ~ #Defaults to current domain from $_Server
         pattern: /.*
         form_login:
              login_path: /login
              check_path: /login_check
              default_target_path: /
         logout:
              path: /logout
              target: /
         security: true
         anonymous: true

   access_control:
       - {path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
       - {path: /manage/user, roles: ROLE_ADMIN}
       - {path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY}

